# Generated by Django 5.0.7 on 2024-08-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agro', '0002_agro_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='agro',
            name='max_quantity',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agro',
            name='min_quantity',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agro',
            name='unit',
            field=models.CharField(choices=[('kilogramo', 'Kilogramo'), ('gramos', 'Gramos'), ('unidades', 'Unidades')], default=5, max_length=15),
            preserve_default=False,
        ),
    ]
