# Generated by Django 5.0.7 on 2024-08-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agro', '0003_agro_max_quantity_agro_min_quantity_agro_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agro',
            name='description',
        ),
        migrations.AddField(
            model_name='agro',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
